const mockNewsArticles = {
  status: "OK",
  copyright:
    "Copyright (c) 2023 The New York Times Company. All Rights Reserved.",
  section: "home",
  last_updated: "2023-01-03T12:27:28-05:00",
  num_results: 34,
  results: [
    {
      section: "us",
      subsection: "politics",
      title: "Who Are the Republicans Opposing McCarthy’s Speaker Bid?",
      abstract:
        "The rebellion has been led by a small but vocal group of ultraconservative Republicans. But there are other, less-known defectors who could help scuttle the G.O.P. leader’s candidacy.",
      url: "https://www.nytimes.com/2023/01/03/us/politics/kevin-mccarthy-republican-opposition.html",
      uri: "nyt://article/d9685c50-3258-52c5-aa3d-4fba6c7a43a1",
      byline: "By Catie Edmondson",
      item_type: "Article",
      updated_date: "2023-01-03T11:45:52-05:00",
      created_date: "2023-01-03T05:00:13-05:00",
      published_date: "2023-01-03T05:00:13-05:00",
      material_type_facet: "",
      kicker: "",
      des_facet: ["United States Politics and Government"],
      org_facet: ["House of Representatives", "Republican Party"],
      per_facet: [
        "McCarthy, Kevin (1965- )",
        "Biggs, Andy (1958- )",
        "Gaetz, Matt",
        "Good, Bob (1965- )",
        "Ogles, Andy",
        "Perry, Scott G (1962- )",
        "Rosendale, Matt",
        "Roy, Chip (1972- )",
        "Norman, Ralph W Jr (1953- )",
        "Bishop, J Daniel (1964- )",
        "Crane, Eli (1980- )",
        "Luna, Anna Paulina",
      ],
      geo_facet: [],
      multimedia: [
        {
          url: "https://static01.nyt.com/images/2023/01/03/multimedia/03dc-rebels-1-e81f/03dc-rebels-1-e81f-superJumbo.jpg",
          format: "Super Jumbo",
          height: 1365,
          width: 2048,
          type: "image",
          subtype: "photo",
          caption:
            "Representative Kevin McCarthy must secure near unanimity among Republicans to win the speaker’s job.",
          copyright: "Mikayla Whitmore for The New York Times",
        },
        {
          url: "https://static01.nyt.com/images/2023/01/03/multimedia/03dc-rebels-1-e81f/03dc-rebels-1-e81f-threeByTwoSmallAt2X.jpg",
          format: "threeByTwoSmallAt2X",
          height: 400,
          width: 600,
          type: "image",
          subtype: "photo",
          caption:
            "Representative Kevin McCarthy must secure near unanimity among Republicans to win the speaker’s job.",
          copyright: "Mikayla Whitmore for The New York Times",
        },
        {
          url: "https://static01.nyt.com/images/2023/01/03/multimedia/03dc-rebels-1-e81f/03dc-rebels-1-e81f-thumbLarge.jpg",
          format: "Large Thumbnail",
          height: 150,
          width: 150,
          type: "image",
          subtype: "photo",
          caption:
            "Representative Kevin McCarthy must secure near unanimity among Republicans to win the speaker’s job.",
          copyright: "Mikayla Whitmore for The New York Times",
        },
      ],
      short_url: "https://nyti.ms/3Z59AEq",
    },
    {
      section: "us",
      subsection: "politics",
      title: "George Santos Comes to Washington. It Could Be Awkward.",
      abstract:
        "On the first day of the 118th Congress, the representative-elect, a Republican who has made false claims about his background, education and finances, will bring his saga to Capitol Hill.",
      url: "https://www.nytimes.com/2023/01/03/us/politics/george-santos-congress.html",
      uri: "nyt://article/9d74d5a2-75e5-5a2d-8ff7-32b6ffa2d7dd",
      byline: "By Annie Karni",
      item_type: "Article",
      updated_date: "2023-01-03T11:06:21-05:00",
      created_date: "2023-01-03T05:00:20-05:00",
      published_date: "2023-01-03T05:00:20-05:00",
      material_type_facet: "",
      kicker: "",
      des_facet: [
        "United States Politics and Government",
        "Midterm Elections (2022)",
      ],
      org_facet: ["House of Representatives"],
      per_facet: ["Santos, George (1988- )"],
      geo_facet: ["Long Island (NY)"],
      multimedia: [
        {
          url: "https://static01.nyt.com/images/2023/01/03/us/politics/03dc-santos/03dc-santos-superJumbo.jpg",
          format: "Super Jumbo",
          height: 1365,
          width: 2048,
          type: "image",
          subtype: "photo",
          caption:
            "George Santos is under the shadow of active investigations by federal and local prosecutors into potential criminal activity during his two congressional campaigns.",
          copyright: "Alejandra Villa Loarca/Newsday RM, via Getty Images",
        },
        {
          url: "https://static01.nyt.com/images/2023/01/03/us/politics/03dc-santos/03dc-santos-threeByTwoSmallAt2X.jpg",
          format: "threeByTwoSmallAt2X",
          height: 400,
          width: 600,
          type: "image",
          subtype: "photo",
          caption:
            "George Santos is under the shadow of active investigations by federal and local prosecutors into potential criminal activity during his two congressional campaigns.",
          copyright: "Alejandra Villa Loarca/Newsday RM, via Getty Images",
        },
        {
          url: "https://static01.nyt.com/images/2023/01/03/us/politics/03dc-santos/03dc-santos-thumbLarge.jpg",
          format: "Large Thumbnail",
          height: 150,
          width: 150,
          type: "image",
          subtype: "photo",
          caption:
            "George Santos is under the shadow of active investigations by federal and local prosecutors into potential criminal activity during his two congressional campaigns.",
          copyright: "Alejandra Villa Loarca/Newsday RM, via Getty Images",
        },
      ],
      short_url: "https://nyti.ms/3YYoJYa",
    },
    {
      section: "sports",
      subsection: "football",
      title:
        "Damar Hamlin of Buffalo Bills in Critical Condition After Collapsing During N.F.L. Game",
      abstract:
        "Hamlin, a 24-year-old safety, went into cardiac arrest after being hit, but his heartbeat was restored by medical personnel, the Bills said. The game against the Cincinnati Bengals was postponed.",
      url: "https://www.nytimes.com/2023/01/02/sports/football/damar-hamlin-bills-hit.html",
      uri: "nyt://article/f5b31647-781b-5398-8c43-20133cadd074",
      byline: "By Emmanuel Morgan and Ken Belson",
      item_type: "Article",
      updated_date: "2023-01-03T11:37:50-05:00",
      created_date: "2023-01-02T21:21:35-05:00",
      published_date: "2023-01-02T21:21:35-05:00",
      material_type_facet: "",
      kicker: "",
      des_facet: ["Football", "Sports Injuries"],
      org_facet: [
        "Buffalo Bills",
        "Cincinnati Bengals",
        "National Football League",
      ],
      per_facet: ["Hamlin, Damar (1998- )"],
      geo_facet: [],
      multimedia: [
        {
          url: "https://static01.nyt.com/images/2023/01/02/multimedia/02nfl-bills-ambulance-1-a4d3/02nfl-bills-ambulance-1-a4d3-superJumbo.jpg",
          format: "Super Jumbo",
          height: 1365,
          width: 2048,
          type: "image",
          subtype: "photo",
          caption:
            "An ambulance carrying Damar Hamlin left the field at Paycor Stadium during the game between the Bills and Bengals on Monday night.",
          copyright: "Dylan Buell/Getty Images",
        },
        {
          url: "https://static01.nyt.com/images/2023/01/02/multimedia/02nfl-bills-ambulance-1-a4d3/02nfl-bills-ambulance-1-a4d3-threeByTwoSmallAt2X.jpg",
          format: "threeByTwoSmallAt2X",
          height: 400,
          width: 600,
          type: "image",
          subtype: "photo",
          caption:
            "An ambulance carrying Damar Hamlin left the field at Paycor Stadium during the game between the Bills and Bengals on Monday night.",
          copyright: "Dylan Buell/Getty Images",
        },
        {
          url: "https://static01.nyt.com/images/2023/01/02/multimedia/02nfl-bills-ambulance-1-a4d3/02nfl-bills-ambulance-1-a4d3-thumbLarge.jpg",
          format: "Large Thumbnail",
          height: 150,
          width: 150,
          type: "image",
          subtype: "photo",
          caption:
            "An ambulance carrying Damar Hamlin left the field at Paycor Stadium during the game between the Bills and Bengals on Monday night.",
          copyright: "Dylan Buell/Getty Images",
        },
      ],
      short_url: "https://nyti.ms/3Q6QhXq",
    },
    {
      section: "sports",
      subsection: "football",
      title: "N.F.L. Faces New Injury Crisis With Hamlin’s Collapse",
      abstract:
        "Pro football has never been more popular, or lucrative, but the collapse of Damar Hamlin during a prime-time game was a reminder of the sport’s inherent risk.",
      url: "https://www.nytimes.com/2023/01/03/sports/football/nfl-damar-hamlin-bills-injury.html",
      uri: "nyt://article/b399ae6f-858b-52d7-996b-aabe3f69d766",
      byline: "By Ken Belson",
      item_type: "Article",
      updated_date: "2023-01-03T12:21:12-05:00",
      created_date: "2023-01-03T10:29:10-05:00",
      published_date: "2023-01-03T10:29:10-05:00",
      material_type_facet: "",
      kicker: "",
      des_facet: ["Sports Injuries", "Football", "Concussions"],
      org_facet: [
        "Buffalo Bills",
        "Cincinnati Bengals",
        "National Football League",
      ],
      per_facet: ["Vincent, Troy", "Hamlin, Damar (1998- )"],
      geo_facet: [],
      multimedia: [
        {
          url: "https://static01.nyt.com/images/2023/01/03/multimedia/03nfl-ledeall-1-9096/03nfl-ledeall-1-9096-superJumbo.jpg",
          format: "Super Jumbo",
          height: 1516,
          width: 2048,
          type: "image",
          subtype: "photo",
          caption:
            "Buffalo Bills players stayed on the field as an ambulance carried away safety Damar Hamlin. Hamlin was in critical condition on Tuesday morning.",
          copyright: "Joseph Maiorana/USA Today Sports, via Reuters",
        },
        {
          url: "https://static01.nyt.com/images/2023/01/03/multimedia/03nfl-ledeall-1-9096/03nfl-ledeall-1-9096-threeByTwoSmallAt2X.jpg",
          format: "threeByTwoSmallAt2X",
          height: 400,
          width: 600,
          type: "image",
          subtype: "photo",
          caption:
            "Buffalo Bills players stayed on the field as an ambulance carried away safety Damar Hamlin. Hamlin was in critical condition on Tuesday morning.",
          copyright: "Joseph Maiorana/USA Today Sports, via Reuters",
        },
        {
          url: "https://static01.nyt.com/images/2023/01/03/multimedia/03nfl-ledeall-1-9096/03nfl-ledeall-1-9096-thumbLarge.jpg",
          format: "Large Thumbnail",
          height: 150,
          width: 150,
          type: "image",
          subtype: "photo",
          caption:
            "Buffalo Bills players stayed on the field as an ambulance carried away safety Damar Hamlin. Hamlin was in critical condition on Tuesday morning.",
          copyright: "Joseph Maiorana/USA Today Sports, via Reuters",
        },
      ],
      short_url: "https://nyti.ms/3Qej6RW",
    },
    {
      section: "business",
      subsection: "",
      title: "Natural Gas Prices in Europe Fall to Pre-Invasion Levels",
      abstract:
        "Warm weather, alternatives to Russian gas and a buildup of storage all help. But prices remain high for consumers and industry.",
      url: "https://www.nytimes.com/2023/01/03/business/europe-natural-gas-prices.html",
      uri: "nyt://article/d7682d9c-852a-5ab2-86a9-821954ec4458",
      byline: "By Stanley Reed",
      item_type: "Article",
      updated_date: "2023-01-03T10:58:11-05:00",
      created_date: "2023-01-03T09:59:41-05:00",
      published_date: "2023-01-03T09:59:41-05:00",
      material_type_facet: "",
      kicker: "",
      des_facet: [
        "Natural Gas",
        "Prices (Fares, Fees and Rates)",
        "Russian Invasion of Ukraine (2022)",
      ],
      org_facet: ["European Union"],
      per_facet: [],
      geo_facet: ["Europe"],
      multimedia: [
        {
          url: "https://static01.nyt.com/images/2023/01/03/multimedia/03eurogas-1-d9a3/03eurogas-1-d9a3-superJumbo.jpg",
          format: "Super Jumbo",
          height: 1366,
          width: 2048,
          type: "image",
          subtype: "photo",
          caption:
            "Ships at a Dutch port pump liquefied natural gas brought from the Gulf Coast of the United States.",
          copyright: "Ilvy Njiokiktjien for The New York Times",
        },
        {
          url: "https://static01.nyt.com/images/2023/01/03/multimedia/03eurogas-1-d9a3/03eurogas-1-d9a3-threeByTwoSmallAt2X.jpg",
          format: "threeByTwoSmallAt2X",
          height: 400,
          width: 600,
          type: "image",
          subtype: "photo",
          caption:
            "Ships at a Dutch port pump liquefied natural gas brought from the Gulf Coast of the United States.",
          copyright: "Ilvy Njiokiktjien for The New York Times",
        },
        {
          url: "https://static01.nyt.com/images/2023/01/03/multimedia/03eurogas-1-d9a3/03eurogas-1-d9a3-thumbLarge.jpg",
          format: "Large Thumbnail",
          height: 150,
          width: 150,
          type: "image",
          subtype: "photo",
          caption:
            "Ships at a Dutch port pump liquefied natural gas brought from the Gulf Coast of the United States.",
          copyright: "Ilvy Njiokiktjien for The New York Times",
        },
      ],
      short_url: "https://nyti.ms/3Cjf4BE",
    },
    {
      section: "arts",
      subsection: "design",
      title: "Tanks and Teddy Bears: Ukrainian Children Paint the War",
      abstract:
        "An artist from Lviv has brought works by young people affected by the Russian invasion to a museum in Chicago’s Ukrainian enclave.",
      url: "https://www.nytimes.com/2023/01/03/arts/design/ukraine-children-war-art.html",
      uri: "nyt://article/bb94dc56-8c21-534f-9a2d-afe469d2c182",
      byline: "By Julia Jacobs",
      item_type: "Article",
      updated_date: "2023-01-03T11:07:51-05:00",
      created_date: "2023-01-03T11:05:39-05:00",
      published_date: "2023-01-03T11:05:39-05:00",
      material_type_facet: "",
      kicker: "",
      des_facet: [
        "Art",
        "Museums",
        "Russian Invasion of Ukraine (2022)",
        "Children and Childhood",
      ],
      org_facet: ["Ukrainian Institute of Modern Art"],
      per_facet: [],
      geo_facet: ["Chicago (Ill)", "Ukraine", "Lviv (Ukraine)"],
      multimedia: [
        {
          url: "https://static01.nyt.com/images/2022/12/27/multimedia/00ukraine-art-4-f108-promo/00ukraine-art-4-f108-superJumbo.jpg",
          format: "Super Jumbo",
          height: 2048,
          width: 1463,
          type: "image",
          subtype: "photo",
          caption:
            "A 9-year-old boy named Roman depicted the fall of Mariupol, one of the bloodiest battles of Russia’s war against Ukraine. Below, a painting by Daryna, 10.",
          copyright: "Lyndon French for The New York Times",
        },
        {
          url: "https://static01.nyt.com/images/2022/12/27/multimedia/00ukraine-art-4-f108-promo/00ukraine-art-4-f108-promo-threeByTwoSmallAt2X.jpg",
          format: "threeByTwoSmallAt2X",
          height: 400,
          width: 600,
          type: "image",
          subtype: "photo",
          caption:
            "A 9-year-old boy named Roman depicted the fall of Mariupol, one of the bloodiest battles of Russia’s war against Ukraine. Below, a painting by Daryna, 10.",
          copyright: "Lyndon French for The New York Times",
        },
        {
          url: "https://static01.nyt.com/images/2022/12/27/multimedia/00ukraine-art-4-f108-promo/00ukraine-art-4-f108-promo-thumbLarge.jpg",
          format: "Large Thumbnail",
          height: 150,
          width: 150,
          type: "image",
          subtype: "photo",
          caption:
            "A 9-year-old boy named Roman depicted the fall of Mariupol, one of the bloodiest battles of Russia’s war against Ukraine. Below, a painting by Daryna, 10.",
          copyright: "Lyndon French for The New York Times",
        },
      ],
      short_url: "https://nyti.ms/3WYcKIk",
    },
  ],
};

export default mockNewsArticles;
